#!/usr/bin/env python3
import json, os
from colorama import Fore, Back, Style

file = '/home/cleamoon/.todo_list'

data = json.load(open(file))

def display():
    i = 1
    for item in data:
        name = str(i) + ': ' + item['name']
        status_on = False
        deadline_on = False
        if 'status' in item:
            status = (item['status'] == "done")
            status_on = True
        if 'deadline' in item:
            deadline = item['deadline']
            deadline_on = True
        if deadline_on:
            output = name + ' : deadline on ' + deadline
        else:
            output = name
        if status_on:
            if status == True:
                print(Style.DIM + Fore.WHITE + output)
            else:
                print(Fore.RED + Style.BRIGHT + output)
        else:
            print(Fore.MAGENTA + output)
        print(Style.RESET_ALL, end='')
        i += 1

display()

while True:
    com = input('Command: ').split()
    if com[0] == 'add':
        data.append({'name': (' '.join(com[1:])), 'status': 'working'})
    elif com[0] == 'remove':
        data.pop(int(com[1])-1)
    elif com[0] == 'quit':
        break
    elif com[0] == 'exit':
        break
    elif com[0] == 'display':
        display()
    elif com[0] == 'disp':
        display()
    elif com[0] == 'write':
        json.dump(data, open(file, 'w'))
    elif com[0] == 'done':
        data[int(com[1])-1]['status'] = 'done'
    else:
        print('Command not found.')


json.dump(data, open(file, 'w'))
